import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col" data-surface="marketing">
      <Navigation />

      <div className="pt-24 pb-16 flex-1">
        <div className="container max-w-4xl">
          <h1 className="mb-8">Terms of Service</h1>

          <div className="prose prose-slate max-w-none">
            <p className="text-lg text-muted-foreground mb-8">
              Effective date: December 15, 2024
            </p>

            <p>
              These Terms govern access to and use of Lead Engine OS ("Service"), operated by Kiasu Family Trust ("Company", "we", "us").
            </p>

            <h2>1. Services</h2>
            <p>
              The Service provides subscription-based fulfillment deliverables, which may include landing pages, blog content, SEO improvements, reporting, and related materials, subject to plan limits.
            </p>

            <h2>2. Subscriptions, Billing, and Renewal</h2>
            <p>
              Subscriptions renew automatically each billing period unless canceled before renewal.
              Pricing, plan limits, and included deliverables are shown at checkout and in the customer portal.
            </p>
            <p>
              <strong>No setup fees.</strong> There are no setup, onboarding, or hidden fees.
            </p>

            <h2>3. Cancellation and Pausing</h2>
            <p>
              Customers may cancel according to the instructions in the portal.
              If "pause" is offered, pause rules will be shown in the portal.
            </p>

            <h2>4. Refunds</h2>
            <p>
              <strong>14-day money-back guarantee.</strong> If you are not satisfied within the first 14 days of your initial subscription, you may request a full refund by contacting support@leadengine.kiasufamilytrust.org.
            </p>
            <p>
              After 14 days, subscriptions are non-refundable.
            </p>

            <h2>5. Customer Responsibilities</h2>
            <p>
              You are responsible for the accuracy of information you provide and for maintaining access credentials you choose to connect.
              You agree not to use the Service for unlawful, deceptive, or harmful activity.
            </p>

            <h2>6. No Guarantees</h2>
            <p>
              We do not guarantee specific outcomes, rankings, revenue, or performance.
              Benchmarks and illustrative examples are informational only.
            </p>

            <h2>7. Intellectual Property</h2>
            <p>
              We retain ownership of the Service, software, and templates.
              Upon payment, you receive a license to use delivered materials for your business.
            </p>

            <h2>8. Content Ownership</h2>
            <p>
              <strong>Your Content:</strong> You retain all rights to content you provide to us (business information, keywords, brand assets).
            </p>
            <p>
              <strong>Generated Content:</strong> All content generated by our Service (blog posts, landing pages, SEO recommendations) becomes your property upon delivery. You may use, modify, and publish this content without restriction.
            </p>

            <h2>9. WordPress Integration</h2>
            <p>
              If you connect your WordPress site to our Service:
            </p>
            <ul>
              <li>You grant us access to publish content on your behalf</li>
              <li>You can enable/disable auto-publishing at any time</li>
              <li>We will not modify or delete existing content without your request</li>
              <li>You are responsible for maintaining backups of your website</li>
            </ul>

            <h2>10. Limitation of Liability</h2>
            <p>
              To the maximum extent allowed by law, the Company is not liable for indirect, incidental, special, or consequential damages.
              Our total liability is limited to the amount paid for the Service in the last billing period.
            </p>

            <h2>11. Governing Law and Venue (Puerto Rico)</h2>
            <p>
              These Terms are governed by the laws of the Commonwealth of Puerto Rico, without regard to conflict of law principles.
            </p>
            <p>
              Unless you and the Company agree otherwise in writing, any dispute, claim, or controversy arising out of or relating to the Service or these Terms will be brought in the state or federal courts located in San Juan, Puerto Rico, and you consent to personal jurisdiction and venue in those courts.
            </p>

            <h2>12. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service means acceptance of the updated Terms.
            </p>

            <h2>13. Contact</h2>
            <p>
              Legal inquiries: legal@leadengine.kiasufamilytrust.org
              <br />
              Support: support@leadengine.kiasufamilytrust.org
            </p>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
